### ISSUE TITLE
write implementation for sanToIndex and IndexToSan in ChessBoard class

### ISSUE THREAD

**Issue by Rubeenaks** [mtbar131/ChessPGNReader#5]

**Comment by anubhavchaturvedi** [comment]
can you give me the function signature that you are expecting?

**Comment by Rubeenaks** [comment]
its defined inside the class

**Comment by anubhavchaturvedi** [comment]
@Rubeenaks okay saw it. thanks

**Comment by anubhavchaturvedi** [comment]
done - commit 91b799e7f7342e0ad336fa6914c6db3630c3bd03
